import {
  Activity,
  Banknote,
  Boxes,
  Brain,
  Building2,
  ChartLine,
  CircuitBoard,
  Cpu,
  Database,
  Eye,
  Factory,
  FileSearch,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe2,
  HeartPulse,
  Headset,
  Landmark,
  LayoutGrid,
  LineChart,
  Lock,
  Network,
  Orbit,
  Puzzle,
  Radar,
  Recycle,
  ScanEye,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  Stethoscope,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Name → icon registry. Mock data references icons by string so the data
 * layer stays serializable / CMS-portable. Falls back to a neutral mark.
 */
const registry: Record<string, LucideIcon> = {
  activity: Activity,
  banknote: Banknote,
  boxes: Boxes,
  brain: Brain,
  building: Building2,
  "chart-line": ChartLine,
  circuit: CircuitBoard,
  cpu: Cpu,
  database: Database,
  eye: Eye,
  factory: Factory,
  "file-search": FileSearch,
  flask: FlaskConical,
  gauge: Gauge,
  "git-branch": GitBranch,
  globe: Globe2,
  heart: HeartPulse,
  headset: Headset,
  landmark: Landmark,
  grid: LayoutGrid,
  "line-chart": LineChart,
  lock: Lock,
  network: Network,
  orbit: Orbit,
  puzzle: Puzzle,
  radar: Radar,
  recycle: Recycle,
  "scan-eye": ScanEye,
  settings: Settings2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  target: Target,
  trending: TrendingUp,
  trophy: Trophy,
  users: Users,
  workflow: Workflow,
  zap: Zap,
};

export function getIcon(name: string | undefined): LucideIcon {
  if (!name) return Sparkles;
  return registry[name] ?? Sparkles;
}
